DOCS-5226 GitHub Actions Edits
DataDog/synthetics-ci-github-action pull request #127
Opened 2023-04-12 23:02 UTC by alai97

## Context

Adds a site region shortcode in the GitHub Actions doc page.

## How?

DOCS-5226

## Preview

2023-04-13 08:31 UTC, etnbrd requested changes
Thanks a lot for the improvements 🙏 
Unfortunately, I think it'd be preferable for the github rendering of this markdown to not leak the shortcodes that are used for the internal documentation.
![Screenshot 2023-04-13 at 10 12 51 AM](https://user-images.githubusercontent.com/5691124/231701992-9b62e274-4d58-490d-b350-204f8bdca3c2.png)

2023-04-13 08:31 UTC, etnbrd commented on README.md
> +| `datadog_site`      | string  | _optional_  | The [Datadog site][11]. Your Datadog site is {{< region-param key="dd_site" code="true" >}}. **Default:** `datadoghq.com`.
As per the [documentation about region shortcode](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1183023503/Regions+Sites#Site-Region-Shortcode):
> Note: This shortcode only works in the documentation and dogweb repo. For integrations-core or integrations-extras, use the site region partial.

```suggestion
| `datadog_site`      | string  | _optional_  | The [Datadog site][11]. <!-- partial Your Datadog site is {{< region-param key="dd_site" code="true" >}}. partial --> **Default:** `datadoghq.com`.                                                              |
```

2023-04-19 07:54 UTC, etnbrd approved these changes
LGTM 👍 
Thanks for taking this review into account 🙏

2023-04-21 20:10 UTC, rtrieu approved these changes
LGTM

2023-05-03 11:35 UTC, merged